In [125]:
%config IPCompleter.greedy=True

In [126]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
import glob

In [4]:
path = r'data/' # use your path
all_files = glob.glob(path + "/*.txt")
all_files

['data\\deaths_19992000.txt',
 'data\\deaths_20012002.txt',
 'data\\deaths_20032004.txt',
 'data\\deaths_20052006.txt',
 'data\\deaths_20072008.txt',
 'data\\deaths_20092010.txt',
 'data\\deaths_20112012.txt',
 'data\\deaths_20132014.txt',
 'data\\deaths_20152016.txt',
 'data\\deaths_20172018.txt']

In [5]:
li = []

for filename in all_files:

    df = pd.read_csv(filename, sep='\t', index_col=None, header=0)

    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True)

In [27]:
#df = pd.read_csv('data/deaths_20172018.txt', sep='\t') ## Reading a single file

In [15]:
frame.head(2)

,Notes,Census Region,Census Region Code,ICD-10 113 Cause List,ICD-10 113 Cause List Code,Year,Year Code,Ten-Year Age Groups,Ten-Year Age Groups Code,Gender,Gender Code,Deaths,Population,Crude Rate
0,NaN,Census Region 1: Northeast,CENS-R1,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,1999.0,55-64 years,55-64,Male,M,10.0,2240726,Unreliable
1,NaN,Census Region 1: Northeast,CENS-R1,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,1999.0,65-74 years,65-74,Female,F,24.0,2112718,1.1

In [14]:
frame.tail(2)

,Notes,Census Region,Census Region Code,ICD-10 113 Cause List,ICD-10 113 Cause List Code,Year,Year Code,Ten-Year Age Groups,Ten-Year Age Groups Code,Gender,Gender Code,Deaths,Population,Crude Rate
124016,in information available to individual states ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124017,information can be found at: https://www.cdc.g...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124018 entries, 0 to 124017
Data columns (total 14 columns):
Notes                         658 non-null object
Census Region                 123360 non-null object
Census Region Code            123360 non-null object
ICD-10 113 Cause List         123360 non-null object
ICD-10 113 Cause List Code    123360 non-null object
Year                          123360 non-null float64
Year Code                     123360 non-null float64
Ten-Year Age Groups           123360 non-null object
Ten-Year Age Groups Code      123360 non-null object
Gender                        123360 non-null object
Gender Code                   123360 non-null object
Deaths                        123360 non-null float64
Population                    123360 non-null object
Crude Rate                    123360 non-null object
dtypes: float64(3), object(11)
memory usage: 8.0+ MB

In [7]:
# Drop an entire culumn , In this case 'Notes'
frame_no_nan = frame.drop(columns=['Notes'])

In [12]:
frame_no_nan.head(2)

,Census Region,Census Region Code,ICD-10 113 Cause List,ICD-10 113 Cause List Code,Year,Year Code,Ten-Year Age Groups,Ten-Year Age Groups Code,Gender,Gender Code,Deaths,Population,Crude Rate
0,Census Region 1: Northeast,CENS-R1,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,1999.0,55-64 years,55-64,Male,M,10.0,2240726,Unreliable
1,Census Region 1: Northeast,CENS-R1,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,1999.0,65-74 years,65-74,Female,F,24.0,2112718,1.1

In [9]:
# Get a list of unique values in the Year column
frame_no_nan['Year'].unique()

array([1999., 2000.,   nan, 2001., 2002., 2003., 2004., 2005., 2006.,
       2007., 2008., 2009., 2010., 2011., 2012., 2013., 2014., 2015.,
       2016., 2017., 2018.])

In [10]:
## Get the number of null values in the Year column
frame_no_nan['Year'].isnull().sum()

658

In [41]:
#frame_no_nan.to_csv('death1999_2018.csv', encoding='utf-8')
frame_no_nan4.to_csv('data/death1999_2018v4.csv', encoding='utf-8')

In [20]:
frame_no_nan2 = frame_no_nan.dropna()

In [21]:
frame_no_nan2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123360 entries, 0 to 123953
Data columns (total 13 columns):
Census Region                 123360 non-null object
Census Region Code            123360 non-null object
ICD-10 113 Cause List         123360 non-null object
ICD-10 113 Cause List Code    123360 non-null object
Year                          123360 non-null float64
Year Code                     123360 non-null float64
Ten-Year Age Groups           123360 non-null object
Ten-Year Age Groups Code      123360 non-null object
Gender                        123360 non-null object
Gender Code                   123360 non-null object
Deaths                        123360 non-null float64
Population                    123360 non-null object
Crude Rate                    123360 non-null object
dtypes: float64(3), object(10)
memory usage: 8.5+ MB

In [25]:
frame_no_nan2.head(3)

,Census Region,Census Region Code,ICD-10 113 Cause List,ICD-10 113 Cause List Code,Year,Year Code,Ten-Year Age Groups,Ten-Year Age Groups Code,Gender,Gender Code,Deaths,Population,Crude Rate
0,Census Region 1: Northeast,CENS-R1,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,1999.0,55-64 years,55-64,Male,M,10.0,2240726,Unreliable
1,Census Region 1: Northeast,CENS-R1,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,1999.0,65-74 years,65-74,Female,F,24.0,2112718,1.1
2,Census Region 1: Northeast,CENS-R1,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,1999.0,65-74 years,65-74,Male,M,20.0,1677845,1.2

In [26]:
frame_no_nan2['Year'].isnull().sum()

0

In [27]:
frame_no_nan2.head(3)

,Census Region,Census Region Code,ICD-10 113 Cause List,ICD-10 113 Cause List Code,Year,Year Code,Ten-Year Age Groups,Ten-Year Age Groups Code,Gender,Gender Code,Deaths,Population,Crude Rate
0,Census Region 1: Northeast,CENS-R1,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,1999.0,55-64 years,55-64,Male,M,10.0,2240726,Unreliable
1,Census Region 1: Northeast,CENS-R1,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,1999.0,65-74 years,65-74,Female,F,24.0,2112718,1.1
2,Census Region 1: Northeast,CENS-R1,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,1999.0,65-74 years,65-74,Male,M,20.0,1677845,1.2

In [28]:
frame_no_nan2['Ten-Year Age Groups Code'].unique()

array(['55-64', '65-74', '75-84', '85+', '45-54', '1', '1-4', '15-24',
       '25-34', '35-44', '5-14', 'NS'], dtype=object)

In [29]:
frame_no_nan2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123360 entries, 0 to 123953
Data columns (total 13 columns):
Census Region                 123360 non-null object
Census Region Code            123360 non-null object
ICD-10 113 Cause List         123360 non-null object
ICD-10 113 Cause List Code    123360 non-null object
Year                          123360 non-null float64
Year Code                     123360 non-null float64
Ten-Year Age Groups           123360 non-null object
Ten-Year Age Groups Code      123360 non-null object
Gender                        123360 non-null object
Gender Code                   123360 non-null object
Deaths                        123360 non-null float64
Population                    123360 non-null object
Crude Rate                    123360 non-null object
dtypes: float64(3), object(10)
memory usage: 8.5+ MB

In [30]:
frame_no_nan3 = frame_no_nan2.drop(columns=['Census Region Code', 'Year Code', 'Ten-Year Age Groups Code', 'Gender Code'])

In [31]:
frame_no_nan3.head(5)

,Census Region,ICD-10 113 Cause List,ICD-10 113 Cause List Code,Year,Ten-Year Age Groups,Gender,Deaths,Population,Crude Rate
0,Census Region 1: Northeast,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,55-64 years,Male,10.0,2240726,Unreliable
1,Census Region 1: Northeast,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,65-74 years,Female,24.0,2112718,1.1
2,Census Region 1: Northeast,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,65-74 years,Male,20.0,1677845,1.2
3,Census Region 1: Northeast,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,75-84 years,Female,71.0,1627643,4.4
4,Census Region 1: Northeast,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,75-84 years,Male,51.0,1008566,5.1

In [33]:
frame_no_nan4 = frame_no_nan3.copy()

In [34]:
frame_no_nan4.drop(frame_no_nan4.index[frame_no_nan4['Crude Rate'] == 'Unreliable'], inplace = True)

In [87]:
frame_no_nan4.drop(frame_no_nan4.index[frame_no_nan4['Crude Rate'] == 'Not Applicable'], inplace = True)

In [88]:
frame_no_nan4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 106070 entries, 0 to 106261
Data columns (total 9 columns):
Census Region                 106070 non-null object
ICD-10 113 Cause List         106070 non-null object
ICD-10 113 Cause List Code    106070 non-null object
Year                          106070 non-null float64
Ten-Year Age Groups           106070 non-null object
Gender                        106070 non-null object
Deaths                        106070 non-null float64
Population                    106070 non-null object
Crude Rate                    106070 non-null object
dtypes: float64(2), object(7)
memory usage: 5.3+ MB

In [89]:
frame_no_nan4.head(2)

,Census Region,ICD-10 113 Cause List,ICD-10 113 Cause List Code,Year,Ten-Year Age Groups,Gender,Deaths,Population,Crude Rate
0,Census Region 1: Northeast,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,65-74 years,Female,24.0,2112718,1.1
1,Census Region 1: Northeast,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,65-74 years,Male,20.0,1677845,1.2

In [90]:
frame_no_nan4.reset_index(drop=True, inplace=True)

In [91]:
frame_no_nan4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106070 entries, 0 to 106069
Data columns (total 9 columns):
Census Region                 106070 non-null object
ICD-10 113 Cause List         106070 non-null object
ICD-10 113 Cause List Code    106070 non-null object
Year                          106070 non-null float64
Ten-Year Age Groups           106070 non-null object
Gender                        106070 non-null object
Deaths                        106070 non-null float64
Population                    106070 non-null object
Crude Rate                    106070 non-null object
dtypes: float64(2), object(7)
memory usage: 4.5+ MB

In [92]:
frame_no_nan5 = frame_no_nan4.copy()

In [104]:
# Rename Column Header (indexes) with inplace flag
frame_no_nan5.rename(columns={'Census Region':'Region', 'Ten-Year Age Groups':'Age',
                              'ICD-10 113 Cause List':'ICD-10_Cause', 'ICD-10 113 Cause List Code': 'ICD-10_Code',
                             'Crude Rate':'Death_Rate'}, inplace=True)

In [105]:
frame_no_nan5['Death_Rate'] = pd.to_numeric(frame_no_nan5.Death_Rate) 
frame_no_nan5['Population'] = pd.to_numeric(frame_no_nan5.Population)

In [106]:
frame_no_nan5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106070 entries, 0 to 106069
Data columns (total 9 columns):
Region          106070 non-null object
ICD-10_Cause    106070 non-null object
ICD-10_Code     106070 non-null object
Year            106070 non-null float64
Age             106070 non-null object
Gender          106070 non-null object
Deaths          106070 non-null float64
Population      106070 non-null int64
Death_Rate      106070 non-null float64
dtypes: float64(3), int64(1), object(5)
memory usage: 5.3+ MB

In [107]:
frame_no_nan5.head(2)

,Region,ICD-10_Cause,ICD-10_Code,Year,Age,Gender,Deaths,Population,Death_Rate
0,Census Region 1: Northeast,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,65-74 years,Female,24.0,2112718,1.1
1,Census Region 1: Northeast,"Certain other intestinal infections (A04,A07-A09)",GR113-003,1999.0,65-74 years,Male,20.0,1677845,1.2

In [109]:
# Export of data - progress - nulls, extra columns removed, columns (indexes) renamed
frame_no_nan5.to_csv('data/death1999_2018v5.csv', encoding='utf-8')

In [110]:
# Deep copy dataframe before re-indexing and melting
frame_no_nan6 = frame_no_nan5.copy()

In [111]:
frame_no_nan6.set_index(['Region','Year','Age','Gender'], inplace=True)

In [112]:
frame_no_nan6.head(10)

                                                                                           ICD-10_Cause  \
Region                     Year   Age         Gender
Census Region 1: Northeast 1999.0 65-74 years Female  Certain other intestinal infections (A04,A07-A09)
                                              Male    Certain other intestinal infections (A04,A07-A09)
                                  75-84 years Female  Certain other intestinal infections (A04,A07-A09)
                                              Male    Certain other intestinal infections (A04,A07-A09)
                                  85+ years   Female  Certain other intestinal infections (A04,A07-A09)
                                              Male    Certain other intestinal infections (A04,A07-A09)
                           2000.0 65-74 years Female  Certain other intestinal infections (A04,A07-A09)
                                              Male    Certain other intestinal infections (A04,A07-A09)
                                  75-84 years Female  Certain other intestinal infections (A04,A07-A09)
                                              Male    Certain other intestinal infections (A04,A07-A09)

                                                     ICD-10_Code  Deaths  \
Region                     Year   Age         Gender
Census Region 1: Northeast 1999.0 65-74 years Female   GR113-003    24.0
                                              Male     GR113-003    20.0
                                  75-84 years Female   GR113-003    71.0
                                              Male     GR113-003    51.0
                                  85+ years   Female   GR113-003    86.0
                                              Male     GR113-003    34.0
                           2000.0 65-74 years Female   GR113-003    29.0
                                              Male     GR113-003    27.0
                                  75-84 years Female   GR113-003    63.0
                                              Male     GR113-003    46.0

                                                      Population  Death_Rate
Region                     Year   Age         Gender
Census Region 1: Northeast 1999.0 65-74 years Female     2112718         1.1
                                              Male       1677845         1.2
                                  75-84 years Female     1627643         4.4
                                              Male       1008566         5.1
                                  85+ years   Female      665957        12.9
                                              Male        252186        13.5
                           2000.0 65-74 years Female     2096915         1.4
                                              Male       1671357         1.6
                                  75-84 years Female     1644519         3.8
                                              Male       1021032         4.5

In [113]:
frame_no_nan6.reset_index()

,Region,Year,Age,Gender,ICD-10_Cause,ICD-10_Code,Deaths,Population,Death_Rate
0,Census Region 1: Northeast,1999.0,65-74 years,Female,"Certain other intestinal infections (A04,A07-A09)",GR113-003,24.0,2112718,1.1
1,Census Region 1: Northeast,1999.0,65-74 years,Male,"Certain other intestinal infections (A04,A07-A09)",GR113-003,20.0,1677845,1.2
2,Census Region 1: Northeast,1999.0,75-84 years,Female,"Certain other intestinal infections (A04,A07-A09)",GR113-003,71.0,1627643,4.4
3,Census Region 1: Northeast,1999.0,75-84 years,Male,"Certain other intestinal infections (A04,A07-A09)",GR113-003,51.0,1008566,5.1
4,Census Region 1: Northeast,1999.0,85+ years,Female,"Certain other intestinal infections (A04,A07-A09)",GR113-003,86.0,665957,12.9
...,...,...,...,...,...,...,...,...,...
106065,Census Region 4: West,2018.0,65-74 years,Male,#Enterocolitis due to Clostridium difficile (A...,GR113-136,96.0,3274564,2.9
106066,Census Region 4: West,2018.0,75-84 years,Female,#Enterocolitis due to Clostridium difficile (A...,GR113-136,189.0,1861970,10.2
106067,Census Region 4: West,2018.0,75-84 years,Male,#Enterocolitis due to Clostridium difficile (A...,GR113-136,141.0,1521348,9.3
106068,Census Region 4: West,2018.0,85+ years,Female,#Enterocolitis due to Clostridium difficile (A...,GR113-136,233.0,888532,26.2
106069,Census Region 4: West,2018.0,85+ years,Male,#Enterocolitis due to Clostridium difficile (A...,GR113-136,153.0,536101,28.5

In [114]:
frame_no_nan6.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 106070 entries, (Census Region 1: Northeast, 1999.0, 65-74 years, Female) to (Census Region 4: West, 2018.0, 85+ years, Male)
Data columns (total 5 columns):
ICD-10_Cause    106070 non-null object
ICD-10_Code     106070 non-null object
Deaths          106070 non-null float64
Population      106070 non-null int64
Death_Rate      106070 non-null float64
dtypes: float64(2), int64(1), object(2)
memory usage: 3.6+ MB

In [117]:
frame6_pvt = frame_no_nan6.pivot_table(index=['Region', 'Year','Gender','ICD-10_Cause','ICD-10_Code'], 
                                columns='Age',
                                values='Death_Rate')
# ,'Population','Death_Rate'

In [120]:
frame6_pvt.head(6)

Age                                                                                                      1-4 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112          6.0
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080          NaN
                                         #Alzheimer disease (G30)                           GR113-052          NaN
                                         #Anemias (D50-D64)                                 GR113-045          NaN
                                         #Aortic aneurysm and dissection (I71)              GR113-073          NaN
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127          2.1

Age                                                                                                      15-24 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           14.2
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052            NaN
                                         #Anemias (D50-D64)                                 GR113-045            NaN
                                         #Aortic aneurysm and dissection (I71)              GR113-073            NaN
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            3.0

Age                                                                                                      25-34 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112            9.3
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052            NaN
                                         #Anemias (D50-D64)                                 GR113-045            NaN
                                         #Aortic aneurysm and dissection (I71)              GR113-073            NaN
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            2.8

Age                                                                                                      35-44 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           12.0
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052            NaN
                                         #Anemias (D50-D64)                                 GR113-045            NaN
                                         #Aortic aneurysm and dissection (I71)              GR113-073            NaN
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            3.1

Age                                                                                                      45-54 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           11.0
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052            NaN
                                         #Anemias (D50-D64)                                 GR113-045            0.7
                                         #Aortic aneurysm and dissection (I71)              GR113-073            0.6
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            1.4

Age                                                                                                      5-14 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           3.7
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080           NaN
                                         #Alzheimer disease (G30)                           GR113-052           NaN
                                         #Anemias (D50-D64)                                 GR113-045           NaN
                                         #Aortic aneurysm and dissection (I71)              GR113-073           NaN
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127           0.6

Age                                                                                                      55-64 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           14.0
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052            1.7
                                         #Anemias (D50-D64)                                 GR113-045            0.8
                                         #Aortic aneurysm and dissection (I71)              GR113-073            2.8
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            1.1

Age                                                                                                      65-74 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           25.3
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052           13.7
                                         #Anemias (D50-D64)                                 GR113-045            2.7
                                         #Aortic aneurysm and dissection (I71)              GR113-073           12.4
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            1.0

Age                                                                                                      75-84 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           70.8
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052           98.5
                                         #Anemias (D50-D64)                                 GR113-045           10.1
                                         #Aortic aneurysm and dissection (I71)              GR113-073           34.3
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            1.3

Age                                                                                                      85+ years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112        215.3
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080          4.8
                                         #Alzheimer disease (G30)                           GR113-052        499.1
                                         #Anemias (D50-D64)                                 GR113-045         40.4
                                         #Aortic aneurysm and dissection (I71)              GR113-073         65.9
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127          NaN

Age                                                                                                      < 1 year
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112        10.2
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080         NaN
                                         #Alzheimer disease (G30)                           GR113-052         NaN
                                         #Anemias (D50-D64)                                 GR113-045         NaN
                                         #Aortic aneurysm and dissection (I71)              GR113-073         NaN
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127         NaN

In [129]:
frame6_pvt.reset_index()

Age,Region,Year,Gender,ICD-10_Cause,ICD-10_Code,1-4 years,15-24 years,25-34 years,35-44 years,45-54 years,5-14 years,55-64 years,65-74 years,75-84 years,85+ years,< 1 year
0,Census Region 1: Northeast,1999.0,Female,"#Accidents (unintentional injuries) (V01-X59,Y...",GR113-112,6.0,14.2,9.3,12.0,11.0,3.7,14.0,25.3,70.8,215.3,10.2
1,Census Region 1: Northeast,1999.0,Female,#Acute bronchitis and bronchiolitis (J20-J21),GR113-080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.8,NaN
2,Census Region 1: Northeast,1999.0,Female,#Alzheimer disease (G30),GR113-052,NaN,NaN,NaN,NaN,NaN,NaN,1.7,13.7,98.5,499.1,NaN
3,Census Region 1: Northeast,1999.0,Female,#Anemias (D50-D64),GR113-045,NaN,NaN,NaN,NaN,0.7,NaN,0.8,2.7,10.1,40.4,NaN
4,Census Region 1: Northeast,1999.0,Female,#Aortic aneurysm and dissection (I71),GR113-073,NaN,NaN,NaN,NaN,0.6,NaN,2.8,12.4,34.3,65.9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16759,Census Region 4: West,2018.0,Male,Pneumonia (J12-J18),GR113-078,NaN,0.4,0.7,1.7,4.2,NaN,13.1,27.4,86.0,346.9,NaN
16760,Census Region 4: West,2018.0,Male,Renal failure (N17-N19),GR113-100,NaN,NaN,0.5,1.1,4.6,NaN,11.0,26.4,68.3,214.0,NaN
16761,Census Region 4: West,2018.0,Male,"Symptoms, signs and abnormal clinical and labo...",GR113-110,1.6,1.4,2.3,2.8,3.8,NaN,7.4,10.0,20.4,106.5,56.4
16762,Census Region 4: West,2018.0,Male,"Transport accidents (V01-V99,Y85)",GR113-113,2.5,20.6,21.7,18.1,19.6,2.1,23.3,22.7,26.5,30.8,NaN
16763,Census Region 4: West,2018.0,Male,"Water, air and space, and other and unspecifie...",GR113-116,NaN,NaN,0.9,0.8,1.2,NaN,1.8,2.4,1.8,NaN,NaN

In [122]:
frame6_pvt.to_csv('data/death1999_2018pivot6.csv', encoding='utf-8')

In [130]:
frame6_pvt.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16764 entries, (Census Region 1: Northeast, 1999.0, Female, #Accidents (unintentional injuries) (V01-X59,Y85-Y86), GR113-112) to (Census Region 4: West, 2018.0, Male, Water, air and space, and other and unspecified transport accidents and their sequelae (V90-V99,Y85), GR113-116)
Data columns (total 11 columns):
1-4 years      2285 non-null float64
15-24 years    5466 non-null float64
25-34 years    8486 non-null float64
35-44 years    11470 non-null float64
45-54 years    13638 non-null float64
5-14 years     3105 non-null float64
55-64 years    14769 non-null float64
65-74 years    15025 non-null float64
75-84 years    15052 non-null float64
85+ years      14018 non-null float64
< 1 year       2756 non-null float64
dtypes: float64(11)
memory usage: 1.5+ MB

In [138]:
selected = frame6_pvt.loc['Census Region 1: Northeast', 1999.0]

In [133]:
frame6_pvt.head(7)

Age                                                                                                      1-4 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112          6.0
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080          NaN
                                         #Alzheimer disease (G30)                           GR113-052          NaN
                                         #Anemias (D50-D64)                                 GR113-045          NaN
                                         #Aortic aneurysm and dissection (I71)              GR113-073          NaN
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127          2.1
                                         #Atherosclerosis (I70)                             GR113-071          NaN

Age                                                                                                      15-24 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           14.2
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052            NaN
                                         #Anemias (D50-D64)                                 GR113-045            NaN
                                         #Aortic aneurysm and dissection (I71)              GR113-073            NaN
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            3.0
                                         #Atherosclerosis (I70)                             GR113-071            NaN

Age                                                                                                      25-34 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112            9.3
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052            NaN
                                         #Anemias (D50-D64)                                 GR113-045            NaN
                                         #Aortic aneurysm and dissection (I71)              GR113-073            NaN
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            2.8
                                         #Atherosclerosis (I70)                             GR113-071            NaN

Age                                                                                                      35-44 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           12.0
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052            NaN
                                         #Anemias (D50-D64)                                 GR113-045            NaN
                                         #Aortic aneurysm and dissection (I71)              GR113-073            NaN
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            3.1
                                         #Atherosclerosis (I70)                             GR113-071            NaN

Age                                                                                                      45-54 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           11.0
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052            NaN
                                         #Anemias (D50-D64)                                 GR113-045            0.7
                                         #Aortic aneurysm and dissection (I71)              GR113-073            0.6
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            1.4
                                         #Atherosclerosis (I70)                             GR113-071            NaN

Age                                                                                                      5-14 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           3.7
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080           NaN
                                         #Alzheimer disease (G30)                           GR113-052           NaN
                                         #Anemias (D50-D64)                                 GR113-045           NaN
                                         #Aortic aneurysm and dissection (I71)              GR113-073           NaN
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127           0.6
                                         #Atherosclerosis (I70)                             GR113-071           NaN

Age                                                                                                      55-64 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           14.0
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052            1.7
                                         #Anemias (D50-D64)                                 GR113-045            0.8
                                         #Aortic aneurysm and dissection (I71)              GR113-073            2.8
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            1.1
                                         #Atherosclerosis (I70)                             GR113-071            1.3

Age                                                                                                      65-74 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           25.3
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052           13.7
                                         #Anemias (D50-D64)                                 GR113-045            2.7
                                         #Aortic aneurysm and dissection (I71)              GR113-073           12.4
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            1.0
                                         #Atherosclerosis (I70)                             GR113-071            4.8

Age                                                                                                      75-84 years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           70.8
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
                                         #Alzheimer disease (G30)                           GR113-052           98.5
                                         #Anemias (D50-D64)                                 GR113-045           10.1
                                         #Aortic aneurysm and dissection (I71)              GR113-073           34.3
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127            1.3
                                         #Atherosclerosis (I70)                             GR113-071           23.3

Age                                                                                                      85+ years  \
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112        215.3
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080          4.8
                                         #Alzheimer disease (G30)                           GR113-052        499.1
                                         #Anemias (D50-D64)                                 GR113-045         40.4
                                         #Aortic aneurysm and dissection (I71)              GR113-073         65.9
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127          NaN
                                         #Atherosclerosis (I70)                             GR113-071        154.4

Age                                                                                                      < 1 year
Region                     Year   Gender ICD-10_Cause                                       ICD-10_Code
Census Region 1: Northeast 1999.0 Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112        10.2
                                         #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080         NaN
                                         #Alzheimer disease (G30)                           GR113-052         NaN
                                         #Anemias (D50-D64)                                 GR113-045         NaN
                                         #Aortic aneurysm and dissection (I71)              GR113-073         NaN
                                         #Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)      GR113-127         NaN
                                         #Atherosclerosis (I70)                             GR113-071         NaN

Age                                                                    1-4 years  \
Gender ICD-10_Cause                                       ICD-10_Code
Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112          6.0
       #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080          NaN
       #Alzheimer disease (G30)                           GR113-052          NaN
       #Anemias (D50-D64)                                 GR113-045          NaN
       #Aortic aneurysm and dissection (I71)              GR113-073          NaN

Age                                                                    15-24 years  \
Gender ICD-10_Cause                                       ICD-10_Code
Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           14.2
       #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
       #Alzheimer disease (G30)                           GR113-052            NaN
       #Anemias (D50-D64)                                 GR113-045            NaN
       #Aortic aneurysm and dissection (I71)              GR113-073            NaN

Age                                                                    25-34 years  \
Gender ICD-10_Cause                                       ICD-10_Code
Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112            9.3
       #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
       #Alzheimer disease (G30)                           GR113-052            NaN
       #Anemias (D50-D64)                                 GR113-045            NaN
       #Aortic aneurysm and dissection (I71)              GR113-073            NaN

Age                                                                    35-44 years  \
Gender ICD-10_Cause                                       ICD-10_Code
Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           12.0
       #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
       #Alzheimer disease (G30)                           GR113-052            NaN
       #Anemias (D50-D64)                                 GR113-045            NaN
       #Aortic aneurysm and dissection (I71)              GR113-073            NaN

Age                                                                    45-54 years  \
Gender ICD-10_Cause                                       ICD-10_Code
Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           11.0
       #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
       #Alzheimer disease (G30)                           GR113-052            NaN
       #Anemias (D50-D64)                                 GR113-045            0.7
       #Aortic aneurysm and dissection (I71)              GR113-073            0.6

Age                                                                    5-14 years  \
Gender ICD-10_Cause                                       ICD-10_Code
Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           3.7
       #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080           NaN
       #Alzheimer disease (G30)                           GR113-052           NaN
       #Anemias (D50-D64)                                 GR113-045           NaN
       #Aortic aneurysm and dissection (I71)              GR113-073           NaN

Age                                                                    55-64 years  \
Gender ICD-10_Cause                                       ICD-10_Code
Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           14.0
       #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
       #Alzheimer disease (G30)                           GR113-052            1.7
       #Anemias (D50-D64)                                 GR113-045            0.8
       #Aortic aneurysm and dissection (I71)              GR113-073            2.8

Age                                                                    65-74 years  \
Gender ICD-10_Cause                                       ICD-10_Code
Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           25.3
       #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
       #Alzheimer disease (G30)                           GR113-052           13.7
       #Anemias (D50-D64)                                 GR113-045            2.7
       #Aortic aneurysm and dissection (I71)              GR113-073           12.4

Age                                                                    75-84 years  \
Gender ICD-10_Cause                                       ICD-10_Code
Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112           70.8
       #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080            NaN
       #Alzheimer disease (G30)                           GR113-052           98.5
       #Anemias (D50-D64)                                 GR113-045           10.1
       #Aortic aneurysm and dissection (I71)              GR113-073           34.3

Age                                                                    85+ years  \
Gender ICD-10_Cause                                       ICD-10_Code
Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112        215.3
       #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080          4.8
       #Alzheimer disease (G30)                           GR113-052        499.1
       #Anemias (D50-D64)                                 GR113-045         40.4
       #Aortic aneurysm and dissection (I71)              GR113-073         65.9

Age                                                                    < 1 year
Gender ICD-10_Cause                                       ICD-10_Code
Female #Accidents (unintentional injuries) (V01-X59,Y8... GR113-112        10.2
       #Acute bronchitis and bronchiolitis (J20-J21)      GR113-080         NaN
       #Alzheimer disease (G30)                           GR113-052         NaN
       #Anemias (D50-D64)                                 GR113-045         NaN
       #Aortic aneurysm and dissection (I71)              GR113-073         NaN